name: build
on:
  push:
    branches:
      - master
    paths:
      - "package.json"
  pull_request:
    branches:
      - master
    paths:
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "master"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm i
      - name: build
        run: |
          pnpm build
      - name: zip
        run: |
          zip -r dist.zip dist
      - id: tag
        name: Generate release tag
        run: |
          SUB_STORE_RELEASE=`node --eval="process.stdout.write(require('./package.json').version)"`
          echo "release_tag=$SUB_STORE_RELEASE" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          generate_release_notes: true
          files: |
            dist.zip
